# NumPy

In [1]:
import numpy as np

### Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(2)

array([0.15510727, 0.14411234])

In [16]:
np.random.rand(3,3)

array([[0.45776734, 0.5643222 , 0.4793677 ],
       [0.44319087, 0.23127773, 0.40119516],
       [0.68392906, 0.01851271, 0.42608341]])

In [17]:
np.random.randn(2)

array([ 0.40393631, -1.94974017])

In [18]:
np.random.randn(3,3)

array([[-0.38994332, -1.09559   , -1.71866098],
       [ 0.11028097,  1.27695353, -0.74344872],
       [ 1.09394168, -1.63829136, -0.50036796]])

In [20]:
np.random.randint(1, 100)

49

In [21]:
np.random.randint(1, 100, 10)

array([43,  7, 62,  4, 32, 59,  3,  1, 35, 13])

### Array Attributes and Methods

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([33, 42,  4,  0, 16, 46, 27, 44, 17, 19])

### Reshape

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr

array([33, 42,  4,  0, 16, 46, 27, 44, 17, 19])

In [30]:
ranarr.max()

46

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmax()

5

In [33]:
ranarr.argmin()

3

### Shape
- It is an attribute not a method

In [34]:
arr.shape

(25,)

In [36]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.reshape(5,5).shape

(5, 5)

In [40]:
arr.dtype

dtype('int32')

### NumPy Indexing and Selection

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Broadcasting

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_arr = arr[0:5]

slice_arr

array([0, 1, 2, 3, 4])

In [51]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [53]:
arr_cpy = arr.copy()

arr_cpy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_cpy[:] = 1
arr_cpy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Indexing a 2D array
- The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [56]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr_2d[1]

array([4, 5, 6])

In [58]:
arr_2d[1,0]

4

In [60]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [64]:
arr_2d[:,:1]

array([[1],
       [4],
       [7]])

In [66]:
arr_2d[:,1:2]

array([[2],
       [5],
       [8]])

In [68]:
arr_2d[:,2:]

array([[3],
       [6],
       [9]])

### Fancy Indexing
- Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [69]:
arr2d = np.zeros((10, 10))

In [70]:
arr_length = arr2d.shape[1]

In [71]:
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [73]:
arr2d[[2,4,8,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

### Selection using brackets

In [74]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [76]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### NumPy Operations

In [77]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
arr / arr

C:\Users\fahad\AppData\Local\Temp\ipykernel_19516\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
1 / arr

C:\Users\fahad\AppData\Local\Temp\ipykernel_19516\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [84]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
np.max(arr)

9

In [88]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [89]:
np.log(arr)

C:\Users\fahad\AppData\Local\Temp\ipykernel_19516\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])